### ISSUE TITLE
[Post-MVP] Package Manager API

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#153]
We are planning to provide a set of APIs for Package Management in kapp-controller that can be used by 
- Software authors to package and distribute their software 
- Software consumers to install that software and manage its lifecycle on a Kubernetes cluster

This epic captures the work that needs to be done post-MVP for Package Management.

**Package Manager API MVP**
The issues that will be a part of the Package Manager API MVP can be tracked from this epic (#87).

**Post MVP**
The following issues will **not** be a part of the Package Manager API MVP and will be released at a later stage.

_Ability to package my software in a consistent way_
- [ ] Package authors should be able to customize how InstalledPackage values get included in templating steps (#122)
- [ ] InstalledPackage authors should be able to provide overlays (#123)

_Discover and consume packages_
- [ ] Package Consumers should be able to search for packages that are available on a cluster (#111)

_Nested Package Repositories_
- [ ] PacakgeRepositories should leverage recursive bundles (#125)

_Auto Updating Scenarios_
[Needs more definition]

_Package Dependency Management_
[Needs more definition]

 _Debugging made easy for Package Authors_
- [ ] Add schema for App CRD (#130)

_Debuggability, Stability & Bugs_ 
- [ ] add caching for pulling images (#85) 
- [ ] From commandline, provide ability to capture output and wait for a reconciliation that is in progress (#56) 
- [ ] Cannot delete App when reconciliation is stuck (#69)
- [ ] App gets stuck deleting if service account is not created (#114)

**Comment by aaronshurley** [comment]
Closing out this issue in favor of creating smaller, more focused epics.
