### ISSUE TITLE
CLI for kapp-controller

### ISSUE THREAD

**Issue by renuy** [carvel-dev/kapp-controller#412]
**Describe the problem/challenge you have**
There is no interface for users to interact with kapp-controller server-side. 

**Describe the solution you'd like**
a CLI which can be used to interact with kapp-controller  

**Milestone 1 -- Parity**
- [x] package available get
- [x] package available list
- [x] package install
  - [x] package installed create (alias to "package install")
  - [x] check values-file existence before trying to do things
- [x] package installed get
- [x] package installed list
- [x] package installed delete
- [x] package installed update
  - [x] check values-file existence before trying to do things
- [x] package repository get
- [x] package repository list
- [x] package repository create
- [x] package repository delete
- [x] package repository update
- [x] Clean up (In Progress)
  - [x] openapi v3 parsing (types)
- [x] Tests (In Progress)
- [x] Update root command name? (kapp -> kctrl???)
- [x] values in/out clean up (single values only supported)
- [x] remove wait for delete of package install
- [x] idempotency of install (already in downstream: https://github.com/vmware-tanzu/tanzu-framework/pull/983)
- [x] PR to develop
- [x] documentation PR listing out commands and workflows (Ongoing and updated [PR](https://github.com/vmware-tanzu/carvel/pull/315))

**Milestone 1 -- Feedback**
- [x] Error out when `--version` is not specified by user while installing package
- [x] Remove `--service-account-name` flag from `package installed update`
- [x] Ensure that if a values secret exists with a key other than `valuesFileKey`, update existing key
    - [x] Blow up if more than one keys already exist
- [x] Update only Fetch field instead of whole Spec when updating a package repository.
- [x] Update reconciliation messages to include resource description
- [x] Remove usage of openapi3 library?
- [x] Remove create namespace flag.
- [x] openapi schema fields should be sorted alpha
- [x] add github action test workflow
- [x] Add examples for commands
- [x] ensure that progress waiting output is not repeated (was prev problem with spinner impl)

**Milestone 2 -- Consuming as library**
- [x] importable command tree
- [x] UI Presentation
- [x] argument passing
- [x] global flags
- [x] Handle legacy Tanzu annotations and carvel annotations better
- [x] compile a list of differences from current tanzu package and kctrl (breaking changes)
- [x] sorting semvers via semver library
- [x] Support stdin input (e.g. -) for values file

**Milestone 3 -- Enhancements**
- [x] get, list, delete commands for app  
- [x] status, kick and pause commands for app 
- [x] tail progress of app installation includes easily grabbing failure information from app
- [x] tail progress of pkgi/pkgr installation using underlying apps
- [x] tail progress in kick and delete for app
- [x] kick, pause and status commands for pkg
- [x] tail progress for kick & delete commands for pkg

**Milestone 4 -- Enhancements**
- [ ] package update of values does not trigger change on PackageInstall, hence wait does not work (#670 )
- [ ] disallow by default use of "default" namespace via --dangerous-allow-use-of-shared-namespace=default,kube-public (#672)
- [ ] support providing ytt overlays (#674 )
- [ ] ability to provide values via various flags (similar to ytt)  (#677 )
- [ ] Improve TTY detection (This is common to most Carvel CLIs and should probably be raised on `go-cli-ui`)
- [ ] `--global` flag for package repo add (#673)
- [ ] wordwrapping (ls/get) (#676)
- [ ] force reconcile now for package repo (may not need this, adding to keep track) (#671 )
- [x] Explore how we can handle secrets better without annotations 
- [ ] Allow users to use a flag to stop using and garbage collect a secret created from values file (#675 )
- [ ] Handle invalid package names better (example: `kctrl pkg i -i contour -p foo`) (#676 )

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
Food for thought:
- How can we best handle resources created (ServiceAccounts, Secrets, ClusterRoles, ClusterRoleBindings) and track them for deletion effectively. (Currently, we plan on using annotations on PackageInstall resources and the resources themselves)
- Do  users wanna dump values fetched from Secret references in a PackageInstall?

**Comment by 100mik** [comment]
@cppforlife vmware-tanzu/tanzu-framework#983 seems to add fallback behaviour for all creates and updates, and improve logs printed while removal and creation of created resources. We have already incorporated these changes

**Comment by jorgemoralespou** [comment]
Could this CLI be also compatible somehow to be a kubectl plugin?

**Comment by 100mik** [comment]
We do have a method which attaches the `package` command tree to a Cobra cmd, since we would like to see the package commands consumed by the package plugin for `tanzu-framework`

(We might have to take a harder look at it if it is used in a kubectl plugin as I believe a bunch of flags might have overlapping names, not sure how that works out)

**Comment by jorgemoralespou** [comment]
Since kapp-controller CLI is targetting kubernetes users, I would really suggest that it's implemented as a kubectl plugin to boost adoption and minimize learning curve. If at the end of the day, this is basically providing the same functionality as the `tanzu package` plugin, it might then be better to just work on making that one standalone as well as tanzu plugin and call it a day.

**Comment by 100mik** [comment]
We do intend to add a set of `app` commands which are intended to improve how our users observe and debug App CRs.

**Comment by danielhelfand** [comment]
Hopefully it is the case that this cli can be applied to both contexts. I think a kubectl plugin would be really worthwhile, and I tend to agree that I was thinking this cli should be more tailored to open source users.

Here's more on creating plugins for kuebctl: https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by joe-kimmel-vmw** [comment]
would it make sense to have a "--force" delete feature that was more powerful than kubectl's? e.g. see this issue: https://github.com/vmware-tanzu/carvel-kapp-controller/issues/416

so i could imagine that this CLI (or kapp itself) could be a place where we add like a `--nuke-it-from-space` flag that:
- removes all finalizers from the CR specified and tries to delete it
- if it's still there sets: `spec.noopDelete=true` on the CR and deletes it again

Just because I can imagine how we _could_ ,  doesn't make it a good idea (similar i think to a theme park filled with dinosaurs?), so i'm asking whether we _should_. :)

**Comment by jorgemoralespou** [comment]
I wouldn't consider introducing a flag to undo things that should not have happened, just for the sake of convenience, a good UX.

**Comment by danielhelfand** [comment]
Some minor UX observations for `kctrl package available get`:

 Why does `kctrl package available get` require the `-p` flag? While trying to use, I couldn't find any examples of using it with the help command. From my own expectations, I was thinking the command was as follows:

```shell
$ kctrl package available get cert-manager.community.tanzu.vmware.com
```

It seems like the flag is not needed, but maybe I am not understanding other design considerations.

Another interesting observation I had with `kctrl package available get` was that there was no message saying no package found for nonexistent packages:

```shell
$ kctrl package available get -p i-dont-exist                       
Target cluster 'https://192.168.64.225:8443' (nodes: minikube)

Name  i-dont-exist  

Version  Released at  

Succeeded
```

It might be nice to do what kubectl does in this scenario which is saying no resources found:

```shell
kubectl get deployments/i-dont-exist         
Error from server (NotFound): deployments.apps "i-dont-exist" not found
```

**Comment by 100mik** [comment]
@joe-kimmel-vmw That does seem like a recurring issue we have to assist users with often if I am not wrong, it definitely makes sense to have something like that albeit with a less "aggressive" name maybe? 🤔

**Comment by 100mik** [comment]
@danielhelfand thanks for pointing that out! we should definitely be saying that we could not find any resources if that is the case while getting a specific resource.

Regarding how we are passing parameters we made the choice of using flags for "passing values" to the CLI rather than having positional arguments as that is a observed pattern across the other Carvel CLIs as well which we wanted to maintain.
Adding examples for the commands is on our radar! I will go ahead and add it to our TODO list!

**Comment by 100mik** [comment]
@jorgemoralespou pointed out that we should allow the users to update a package install to stop referencing a secret. Good catch!

We can update a PackageInstall to stop referencing a Secret and delete the Secret _if_ it was created by the CLI.

As of today if users would want to update the installation to not consume a supplied values file, a workaround is to supply an empty values file. In which case the CLI updates the secret to have an empty values file. 
We could let the users have a less hack way of doing this.

### Option 1
In case the user does not supply a value file, or supplies an empty value file while updating an installation. We could prompt the user to confirm whether they would like to the Secret to dereferenced and deleted (if created by the CLI)

This might not be the best way to go about it as this case will be observed mainly when users are trying to bump the version of their installation.

### Option 2
Another option would be to have a flag like `--delete-unused-secret` or `--dereference-unused-secret` which the user can use in case they want the Secret to be garbage collected if an empty values file or no values file is supplied while updating the installation.
This would probably be the preferred option.

Adding this to the list of AIs for now, let's see how we can approach this.

**Comment by praveenrewar** [comment]
I would prefer `--delete-secret` instead of `--delete-unused-secret` as `unused` could be a bit confusing.

**Comment by 100mik** [comment]
That was my first pref too, I was wondering if somehow the values file being supplied is dynamic, would users want to keep the flag in case they wanna dereference a secret _only if_ the values file supplied is empty. But I guess that is a bit of a stretch.

**Comment by jorgemoralespou** [comment]
I would rather say `--no-values-file` as that's the flag you use when you create the secret. In fact, for the user, the secret is an implementation detail that she might not need to know. She created a package with values-file, and now she decides no values-file is needed. We should take the rest (deleting the secret, etc...) internally.

**Comment by 100mik** [comment]
`--no-values-file` does make sense. I think abstracting the inner workings will benefit users

**Comment by stealthybox** [comment]
On the carvel community call today, we talked about how `kick` has advantages over `reconcile` in that it's shorter to say, less abstract, and also fun.
However it does feel a little bit physical which could mean it's not an optimal word choice.

Then we started talking about how `nudge` feels much nicer.
It's nice and short, a single syllable, and really captures the intent of what you would do if somebody needs a gentle reminder to prioritize something.

For the help text, we would probably also still include the word reconcile to explain/convey what happens.

**Comment by jorgemoralespou** [comment]
> Then we started talking about how nudge feels much nicer

You should probably think about non-native english speakers. I don't even know what `nudge` means. So, I would definitely not know what it does.

**Comment by stealthybox** [comment]
For sure -- `kick`  is maybe a more common word?
I would think that `reconcile` is more obscure than `nudge`, but contextually in the cloud-native space non-native speakers are going to quickly learn what that means.

**Comment by 100mik** [comment]
Closing this off in favour of issues branched out from it.
Thanks to all the awesome folks who engaged with us in this thread ❤️ 
Feel free to raise further concerns, issues or enhancement requests by filing an issue 🚀 
(Adding the `cli` label will us manage them better!)

**Comment by 100mik** [comment]
PS: Added links to the issues that have branched off in the description of this issue
