### ISSUE TITLE
backport fixes & patches to the 0.30.x LTS line

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [carvel-dev/kapp-controller#587]
Proposed is to bring the following over:

- [ ] 
- [x] 615832e5 Fix apiserver watch timeouts (#561)
- [x] 5c964fdd app status: convert all receivers to pointers
- [ ] 0c301139 Bump ytt to v0.37.1
- [x] 6e1557a3 update helm to v3.8.0 (#488)
- [x] a5aeb2ee update photon to 4.0 to resolve CVEs (#454)
- [ ] da0801fb Bump vendir to v0.26.0
- [ ] c6bb5a94 Bump imgpkg to v0.27.0 (#576)
- [ ]

**Comment by joe-kimmel-vmw** [comment]
the three bumps couldn't be cherry-picked bc of changes in our dependencies tracking, so they were ported over with fresh commits.
