### ISSUE TITLE
`kctrl`: Post-alpha refactoring tracker for package authoring commands

### ISSUE THREAD

**Issue by 100mik** [carvel-dev/kapp-controller#827]
Tasks at hand:
- [x] Refactor vendor utils to be a scoped struct with associated functions
- [x] Refactor workflows to move away from the step interface and update them according to refactoring described above
    - [x] Local directory
    - [x] Generic vendir step
    - [x] Git release workflow
    - [x] Files from git repo
    - [x] Helm chart from git repo
    - [x] Helm chart from OCI repository
- [x] Dedup and break up `package init` logic into smaller pieces
- [x] Move away from file utils and use existing art in in-built go packages (`ioutil`, `os`) instead
- [x] Refactor existing structs into packages
- [x] Handle how fetch option is passed between stages better
- [x] Verify that there is no regressions through means of existing tests and a bit of manual testing

**Comment by 100mik** [comment]
This is branching out from work that was ongoing in #766 
In favour of breaking it down into digestible pieces and pulling in the authoring commands into an alpha release for early adopters.
