### ISSUE TITLE
Package Manager API MVP

### ISSUE THREAD

**Issue by vibhas** [carvel-dev/kapp-controller#87]
We are planning to provide a set of APIs for Package Management in kapp-controller that can be used by 
- Software authors to package and distribute their software 
- Software consumers to install that software and manage its lifecycle on a Kubernetes cluster

This epic captures the work that needs to be done for an MVP for Package Management.

**Package Manager API MVP**
The following issues will be a part of the Package Manager API MVP.

Getting Started Guide/Documentation
- [X] Documentation to help package authors package and distribute their software (non-airgapped) (#88)
- [X] Documentation to help package consumers install and manage their software (non-airgapped) (#89)
- [x] Packaging Docs Improvements (#211 )

Ability to package my software in a consistent way
- [X] CRD to package a software (#90)
- [X] Introducing new metadata fields for Package CR (#156)
- [x] Package Authors should be able to provide openAPI schema for configurations in Package CR (#104)
- [X] Split the Package CR into Package CR and PackageVersion CR (#135) 

Discover and consume packages
- [X] CRD to watch a package repository (#91)
- [X] View all the packages available on a cluster (#92)
- [X] CRD to install a package on the cluster (#94)
- [x] Implement package aggregated api server (#119)
- [x] Package repository doesn't have a status field (#109)
- [x] Use ytt flag to accept data values as plain YAML file (#209)
- [ ] [Stretch Goal] Reference (source) PackageRepository in Package CR (#124)
- [x] [Stretch Goal] Authentication against private registry when installing a PackageRepository and an InstalledPackage (#145)

Visibility on the packages installed
- [X] View all the installed packages on a cluster (#95)

Ability to upgrade and uninstall software packages
- [X] Uninstall a package from a cluster (#96)
- [X] Update the installed package when a newer version of the package is available (#97)

Support for Air-gapped Environments
- [x] Package repo reconciler should pass all the packages it is going to install through kbld before installation (#143) 
- [x] Documentation to help package consumers install and manage packages (airgapped) (#134)

Debuggability, Stability & Bugs 
- [X] InstalledPackage controller just selects packages by version and not name (#128)
- [X] Using Package version with a semver pre-release label like 1.0.0-alpha1 fails reconciling (#116)
- [x] Package reconciler should be smarter about enqueueing installed pkgs (#107)
- [x] Improve Visibility of App Deployment Progress (#110) 
- [x] Add more debug info to failing InstalledPackages (#133)
- [X] Users should receive an error when Packaging CRDs do not follow the schema (#117)
- [X] Make More App CR Properties Available Through InstalledPackage CR (#193)
- [x] Namespace Packaging API resources (#203)
- [x] Add validations for Packages and PackageVersions (#165)
- [x] Rename Packaging API groups (#172)  
- [x] When removing an InstalledPackage, kapp-controller should wait for the underlying App CR to be removed (#177)
- [x] [Stretch Goal] Package Repository reconciler should not use an app (#108)

**Post MVP**
The issues that will **not** be a part of the Package Manager API MVP and will be released at a later stage can be tracked from this epic (#153).

**Release Process**
Before we make this MVP Generally Available (GA), we are planning to continuously release Alpha versions to get feedback and help us improve the APIs. The development will be done on the _dev-packaging_ branch and the alpha releases can be consumed using this [installation flow](https://carvel.dev/kapp-controller/docs/latest/install-alpha/). This work will make its way to the _develop_ branch once the APIs are in a stable state.

What is GA?
- Debuggability. Being able to debug when things go wrong.
- Consistency. A consistent workflow is defined. For authoring and consuming packages. Work with a team to ensure that we're meeting their needs.
- Complex use cases. Being prepared for more complex use cases (such as auth to registries, air-gapped cases, being able to include more complex configuration).
- Scalability. What is our target? How many packages are we planning to support? Including searchability experience.
- Maintainability. Some level of tech quality. We could consider a code freeze period to focus on cleanup.

**Comment by danielhelfand** [comment]
Wondering if we can better organize these issues as a [GitHub milestone](https://docs.github.com/en/github/managing-your-work-on-github/about-milestones). However, the associated issues for this epic are listed below:

#88 
#89 
#90 
#91 
#92 
#94 
#95 
#96 
#97

**Comment by vibhas** [comment]
@danielhelfand, we initially thought of using milestones but then kept it at an Epic level as we could not come up with a good distribution. Do you have any ideas on how we could use milestones? cc @aaronshurley

**Comment by vibhas** [comment]
The following two items have been marked as stretch goals for this epic. It is highly likely that we are going to work on them after the MVP is released:
- Reference (source) PackageRepository in Package CR (#124)
- Authentication against private registry when installing a PackageRepository and an InstalledPackage (#145)
