### ISSUE TITLE
imgpkg bundle created during pkg release cmd should have user specified version

### ISSUE THREAD

**Issue by rohitagg2020** [carvel-dev/kapp-controller#873]
**Describe the problem/challenge you have**
imgpkg bundle created during pkg release cmd has a tag `bundle-<TIMESTAMP>. User would like to have an option to override this default behavior with the user-specified version.

**Describe the solution you'd like**
Maybe adding a flag to pkg release cmd which will override this default behavior. or adding user-specified version as another tag while pushing the imgpkg bundle to OCI registry.

**Anything else you would like to add:**
User requested this feature so that by looking at OCI registry, they can figure out which bundle belong to which version and take some action(may be like delete, some automation based on tag).

**Tasks**
- [x] [Proposal](https://hackmd.io/gwKHxicETVm_SprXDwkCZA)
- [x] Introduce a new flag to accept user provided tag during `release` commands. This will override the timestamp tag currently generated by kctrl.
- [ ] End to end test  Add `TestE2EInitAndReleaseByAddingTag`
- [x] Update Documentation
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
Adding on to potential use cases, @ThomasVitale mentioned that they would need to retrieve the bundle pushed for practices around supply chain security. Namely, SLSA and cosign I believe 🤔

**Comment by 100mik** [comment]
Closed with #930
