### ISSUE TITLE
kctrl: Generate the openapi schema for helm chart.

### ISSUE THREAD

**Issue by rohitagg2020** [carvel-dev/kapp-controller#899]
**Describe the problem/challenge you have**
Today, when kctrl is used to package helm chart, it is not generating the openapi schema by reading values.yml. 

**Describe the solution you'd like**
I would like kctrl to generate the openapi schema and be available as part of releasable package.

**Task**:
- [x] Proposal - https://hackmd.io/b436sCy1RnqTkSyjnzGwLg
- [ ] Add flag to disable the generation of openapi schema. FlagName: `generate-openapi-schema`
- [ ] Generate openAPI schema without description
- [ ] Generate openAPI schema with description by translating comments with the below formats. Also, all the comments have to be above the key name without any newline in-between.
- [ ] - "# <KEYNAME> Descritption"
- [ ] - "##  Descritption"
- [ ] - "# Descritption"
- [ ] Write unit test cases.
- [ ] Verify output with different scenarios - mongoDb enterprise operator.
       - Behavior in case of scalar node, if Value is empty.
- [ ] Update `TestE2EInitAndReleaseCases` e2e test cases.
- [ ] Update documentation w.r.t. flag.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
