### ISSUE TITLE
`kctrl`: Allow users to supply values file for PackageInstalls while using the dev command

### ISSUE THREAD

**Issue by 100mik** [carvel-dev/kapp-controller#920]
**Describe the problem/challenge you have**
Users might want to test packages with different sets of values easily using the `dev` command.
As of today the only way to do this is to create a secret with the values on the cluster and refer to it in the package install.

**Describe the solution you'd like**
We need an experience similar to simply passing a  `--values-file` flag .
Only challenge I see is that we need to consider how we deal with multiple PackageInstalls? Could we supply values inline with the PackageInstall somehow?

** Tasks **
- [ ] Add flag for accepting --values-file flag (simpler to use flag over annotation for single package install)
- [ ] Build local config map using the new flag, to be consumed by in memory apps
- [ ] open question - Dev command can have multiple package installs, how do users map it to a specific values file/config map
      - [ ] Values file to map to single packageInstall
      - [ ] If there are multiple package installs and values file flag, error out, asking users to use annotation instead 
      - [ ] Have an annotation to support multiple package installs. (can be used for testing/automated flow)
      - [ ] Can the values file have the PackageInstall for which the value files should be used (instead of annotation).
              eg: piA:
                        k1: v1
                    piB:
                       k2: v2
- [ ] Automated Test
- [ ] Documentation
 
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by 100mik** [comment]
cc: @ThomasVitale looping you in since you were interested in this
